[package]
name = "statuser"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0"
actix-identity = "0.4"
serde = { version = "1.0", features = ["derive"] }
once_cell = "1.8.0"
bcrypt = "0.10.0"
dotenv = "0.15.0"
